version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./db/:/var/lib/postgresql/data
    env_file:
      - ./config/vars.test.env
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/api/
    env_file:
      - ./config/vars.test.env
    ports:
      - "3000:3000"
    depends_on:
      - db